/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servicio.h"

bool_t xdr_get_guid_reply(XDR *xdrs, get_guid_reply *objp) {
    register int32_t *buf;

    if (!xdr_int(xdrs, &objp->guid))
        return FALSE;
    if (!xdr_array(xdrs, (char **) &objp->uids.uids_val, (u_int *) &objp->uids.uids_len, ~0,
                   sizeof(int), (xdrproc_t) xdr_int))
        return FALSE;
    return TRUE;
}

bool_t xdr_gname_linked_list(XDR *xdrs, gname_linked_list *objp) {
    register int32_t *buf;

    if (!xdr_string(xdrs, &objp->gname, ~0))
        return FALSE;
    if (!xdr_pointer(xdrs, (char **) &objp->next, sizeof(gname_linked_list), (xdrproc_t) xdr_gname_linked_list))
        return FALSE;
    return TRUE;
}

bool_t xdr_get_uname_reply_true(XDR *xdrs, get_uname_reply_true *objp) {
    register int32_t *buf;

    if (!xdr_string(xdrs, &objp->uname, ~0))
        return FALSE;
    if (!xdr_pointer(xdrs, (char **) &objp->linked_list, sizeof(gname_linked_list), (xdrproc_t) xdr_gname_linked_list))
        return FALSE;
    return TRUE;
}

bool_t xdr_get_uname_reply(XDR *xdrs, get_uname_reply *objp) {
    register int32_t *buf;

    if (!xdr_bool(xdrs, &objp->exists))
        return FALSE;
    switch (objp->exists) {
        case FALSE:
            break;
        case TRUE:
            if (!xdr_pointer(xdrs, (char **) &objp->get_uname_reply_u.reply, sizeof(get_uname_reply_true),
                             (xdrproc_t) xdr_get_uname_reply_true))
                return FALSE;
            break;
        default:
            return FALSE;
    }
    return TRUE;
}
