/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "servicio.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = {25, 0};

get_guid_reply *get_guid_1(char **argp, CLIENT *clnt) {
    static get_guid_reply clnt_res;

    memset((char *) &clnt_res, 0, sizeof(clnt_res));
    if (clnt_call (clnt, GET_GUID,
                   (xdrproc_t) xdr_wrapstring, (caddr_t) argp,
                   (xdrproc_t) xdr_get_guid_reply, (caddr_t) &clnt_res,
                   TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}

get_uname_reply *get_uname_1(int *argp, CLIENT *clnt) {
    static get_uname_reply clnt_res;

    memset((char *) &clnt_res, 0, sizeof(clnt_res));
    if (clnt_call (clnt, GET_UNAME,
                   (xdrproc_t) xdr_int, (caddr_t) argp,
                   (xdrproc_t) xdr_get_uname_reply, (caddr_t) &clnt_res,
                   TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}
